name: Anne Barga Studio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.33736
title: Anne Barga Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29a04e'
    - '#ea8758'
    - '#0c1416'
    - '#bb252c'
    - '#90cbc6'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
